//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeystoneLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Load()
        {
            this.AuditLogs = new HashSet<AuditLog>();
            this.PODDocuments = new HashSet<PODDocument>();
        }
    
        public int LoadId { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string PickupLocation { get; set; }
        public string DropoffLocation { get; set; }
        public string CargoDescription { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DispatchedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLog> AuditLogs { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PODDocument> PODDocuments { get; set; }
    }
}
