//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeystoneLogistics.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODDocument
    {
        public int PODId { get; set; }
        public Nullable<int> LoadId { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> UploadedAt { get; set; }
        public string Notes { get; set; }
    
        public virtual Load Load { get; set; }
    }
}
